spring:
  main:
    banner-mode: "console"
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.S
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mps?autoReconnect=true&socketTimeout=120000
    username: mps
    password: db_mps
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true